config/routes.rb
Rails.application.routes.draw do

  #localhost:3000/home/index
  get '/elise' => 'home#elise'
  #localhost:3000/elise
  resources :users
  resources :posts
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	def full_name
		first_name + ' ' + last_name
		
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def elise
  	@name = 'Elise'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def set_post
    @post = Post.find(params[:id])
  end

  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(post_params)
    redirect_to @post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to posts_path
  end 

  private

  def post_params
    params.require(:post).permit(:content, :title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #show all users
  #GET req to localhost:3000/users
  def index
    @user = User.all
  end
  #GET req to lh:3000/user/:id/
  #show the form to make a new user
  def edit
    @user = User.find(params[:id])
  end
  #handles form submission makes new user
  def new
    @user = User.new
  end
  #PUT req to lh:3/
  #shows user details page
  def create
    p params
    @user = User.create(user_params)
    redirect_to @user
  end
  #edit shows form for editing the user
  def show
    @user = User.find(params[:id])
    @action = 'Show'
  end
  #handles form submission for updating user
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end
  #destroys the user
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/elise.html.erb
<h1>Home#elise</h1>
<p>Find me in app/views/home/elise.html.erb</p>
<p>My name is <%= @name %></p>
<a href="/home/index">Go Home</a> === <%= link_to "Go Home", home_index_path, class: 'yellow', id: 'blue' %>

<%= link_to "Some Page", some_path %>
<%= link_to "Some Page", some_path %>
<%= link_to "Some Page", some_path %>

app/views/home/index.html.erb
<%= link_to "Elise's Page", elise_path %>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= link_to 'Users Index', users_path %>
  	<%= link_to 'Users New', new_user_path %>
  	<%= link_to 'Post Index', posts_path %>
  	<%= link_to 'Post New', new_post_path %>
  	
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Post#edit</h1>
<p>Find me in app/views/post/edit.html.erb</p>

<%= form_with model: @post do |f| %>
	<%= f.text_field :title %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Post#index</h1>
<p>Welcome to the posts</p>
<% @post.reverse.each do |post| %>
	<h2><%= post.title %></h2>
	<p><%= post.content %></p>
	<%= link_to post.title, post %>
	<%= link_to "Edit", edit_post_path(post) %>
	<%= link_to "Delete", post, method: :delete %>
<% end %>

app/views/posts/new.html.erb
<h1>Post#new</h1>
<p>Find me in app/views/post/new.html.erb</p>

<%= form_for @post do |f| %>
	<%= f.text_field :title, placeholder: "Title" %>
	<%= f.text_area :content, placeholder: "Write your post here!" %>
	<input type="hidden" name="user_id" value="2">
	<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1>Post#show</h1>
<p>Find me in app/views/post/show.html.erb</p>

<h1><%= @post.title %></h1>
<h4>By: <%= @user.first_name %> <%= @user.last_name %></h4>
<p><%= @post.content %></p>

<p><%= link_to "Edit", edit_post_path %> <%= link_to "Destroy", @post,  method: :delete %></p>


<%= link_to "See All Posts", posts_path %>

app/views/users/edit.html.erb
<p>This is <%= @action %></p>

<%= form_with model: @user do |f| %>
	<%= f.text_field :first_name, placeholder: 'First Name' %>
	<%= f.text_field :last_name, placeholder: 'Last Name' %>
	<%= f.text_field :email, placeholder: 'Email' %>
	<%= f.password_field :password, placeholder: 'Password' %>
	<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<p>This is <%= @action %></p>

<p>See all the pretty ponies:</p>

<% @user.reverse.each do |user| %>
	<p><%= user.first_name %> <%= user.last_name %>
	<%= link_to "Show #{user.full_name}", user %> <%= link_to "Edit", edit_user_path(user) %>
	<%= link_to "Destroy", user, method: :delete %></p>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_with model: @user do |f| %>
	<%= f.text_field :first_name, placeholder: 'First Name' %>
	<%= f.text_field :last_name, placeholder: 'Last Name' %>
	<%= f.text_field :email, placeholder: 'Email' %>
	<%= f.password_field :password, placeholder: 'Password' %>
	<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<p>This is <%= @action %></p>

<p>The Selected User <%= @user.first_name %> <%= @user.last_name %>, has an id of <%= @user.id %></p>